language: java
jdk:
- openjdk8
branches:
  only:
  - master
  
before_install:
  - chmod +x gradlew
  
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build"
before_deploy:
   - zip -r my-hobby-page *
   - mkdir -p deploy
   - cp scripts/*.sh deploy/
   - mv my-hobby-page.zip deploy/my-hobby-page.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: iamchan-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: iamchan-build
  key: my-hobby-page.zip
  bundle_type: zip
  application: iamchan-test-webservice
  deployment_group: iamchan-test-webservice-group
  region: ap-northeast-2
  wait-until-deployed: true
notifications:
